### ISSUE TITLE
Crashed: TypeError: superclass mismatch for class Digest::SHA3 (Object is given but was Digest::Base)

### ISSUE THREAD

**Issue by cdesch** [phusion/digest-sha3-ruby#12]
Has anyone run into this issue?

```
racecar_1  | => Crashed: TypeError: superclass mismatch for class Digest::SHA3 (Object is given but was Digest::Base)
racecar_1  | /usr/share/gems/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
racecar_1  | /usr/share/gems/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
racecar_1  | /usr/share/gems/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
racecar_1  | /usr/share/gems/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
racecar_1  | /usr/share/gems/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
racecar_1  | /opt/app-root/src/.gem/ruby/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `block in require'
racecar_1  | /opt/app-root/src/.gem/ruby/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:299:in `load_dependency'
racecar_1  | /opt/app-root/src/.gem/ruby/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `require'
racecar_1  | /usr/share/gems/gems/eth-0.4.12/lib/eth.rb:1:in `<main>'
racecar_1  | /usr/share/gems/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
racecar_1  | /usr/share/gems/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
racecar_1  | /usr/share/gems/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
racecar_1  | /usr/share/gems/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
racecar_1  | /usr/share/gems/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
racecar_1  | /opt/app-root/src/.gem/ruby/gems/bundler-2.2.17/lib/bundler/runtime.rb:66:in `block (2 levels) in require'
racecar_1  | /opt/app-root/src/.gem/ruby/gems/bundler-2.2.17/lib/bundler/runtime.rb:61:in `each'
racecar_1  | /opt/app-root/src/.gem/ruby/gems/bundler-2.2.17/lib/bundler/runtime.rb:61:in `block in require'
racecar_1  | /opt/app-root/src/.gem/ruby/gems/bundler-2.2.17/lib/bundler/runtime.rb:50:in `each'
racecar_1  | /opt/app-root/src/.gem/ruby/gems/bundler-2.2.17/lib/bundler/runtime.rb:50:in `require'
racecar_1  | /opt/app-root/src/.gem/ruby/gems/bundler-2.2.17/lib/bundler.rb:173:in `require'
racecar_1  | /opt/app/config/application.rb:20:in `<top (required)>'
racecar_1  | /opt/app/config/environment.rb:2:in `require_relative'
racecar_1  | /opt/app/config/environment.rb:2:in `<top (required)>'
racecar_1  | /opt/app-root/src/.gem/ruby/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `require'
racecar_1  | /opt/app-root/src/.gem/ruby/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `block in require'
racecar_1  | /opt/app-root/src/.gem/ruby/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:299:in `load_dependency'
racecar_1  | /opt/app-root/src/.gem/ruby/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `require'
racecar_1  | /usr/share/gems/gems/racecar-2.2.0/lib/racecar/rails_config_file_loader.rb:17:in `load!'
racecar_1  | /usr/share/gems/gems/racecar-2.2.0/lib/racecar/cli.rb:26:in `run'
racecar_1  | /usr/share/gems/gems/racecar-2.2.0/lib/racecar/cli.rb:13:in `main'
racecar_1  | /usr/share/gems/gems/racecar-2.2.0/exe/racecar:9:in `start'
racecar_1  | /usr/share/gems/gems/racecar-2.2.0/exe/racecar:44:in `<top (required)>'
racecar_1  | /usr/bin/racecar:23:in `load'
racecar_1  | /usr/bin/racecar:23:in `<top (required)>'
racecar_1  | /opt/app-root/src/.gem/ruby/gems/bundler-2.2.17/lib/bundler/cli/exec.rb:63:in `load'
racecar_1  | /opt/app-root/src/.gem/ruby/gems/bundler-2.2.17/lib/bundler/cli/exec.rb:63:in `kernel_load'
racecar_1  | /opt/app-root/src/.gem/ruby/gems/bundler-2.2.17/lib/bundler/cli/exec.rb:28:in `run'
racecar_1  | /opt/app-root/src/.gem/ruby/gems/bundler-2.2.17/lib/bundler/cli.rb:494:in `exec'
racecar_1  | /opt/app-root/src/.gem/ruby/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
racecar_1  | /opt/app-root/src/.gem/ruby/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
racecar_1  | /opt/app-root/src/.gem/ruby/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
racecar_1  | /opt/app-root/src/.gem/ruby/gems/bundler-2.2.17/lib/bundler/cli.rb:30:in `dispatch'
racecar_1  | /opt/app-root/src/.gem/ruby/gems/bundler-2.2.17/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
racecar_1  | /opt/app-root/src/.gem/ruby/gems/bundler-2.2.17/lib/bundler/cli.rb:24:in `start'
racecar_1  | /opt/app-root/src/.gem/ruby/gems/bundler-2.2.17/exe/bundle:49:in `block in <top (required)>'
racecar_1  | /opt/app-root/src/.gem/ruby/gems/bundler-2.2.17/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
racecar_1  | /opt/app-root/src/.gem/ruby/gems/bundler-2.2.17/exe/bundle:37:in `<top (required)>'
racecar_1  | /opt/app-root/src/bin/bundle:23:in `load'
racecar_1  | /opt/app-root/src/bin/bundle:23:in `<main>'
```

**Comment by mathieujobin** [comment]
I think we can close this, the gem in the backtrace `eth` no longer depend on this gem.

https://github.com/q9f/eth.rb/blob/main/eth.gemspec

**Comment by q9f** [comment]
Indeed. Also, using the renamed Keccak gem, the namespace clash is no longer happening between Keccak and the real Sha3 gems.

https://github.com/q9f/keccak.rb

**Comment by cdesch** [comment]
@q9f  @mathieujobin I will close the issue. Thank you
